puts "This is My First program in Ruby."
puts "This is My First program in Ruby."
puts "This is My First program in Ruby."
puts "This is My First program in Ruby."
puts "This is My First program in Ruby."